version: '3.3'
services:
  vulnerableapache:
    build: .
    container_name: vulnerable_apache
    hostname: vulnerable_apache
    ports:
      - 8001:80
    volumes:
      - ./Apache:/usr/local/apache2/conf  